### ISSUE TITLE
CreateDefaultCharToDB & SaveDefaultCharToDB　Error

### ISSUE THREAD

**Issue by fumitti** [chantake/MituyaProject#50]
[09:27:35] [Server thread/ERROR]: SaveDefaultCharToDB
java.sql.SQLException: Field 'uuid' doesn't have a default value
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.chantake.MituyaProject.Player.PlayerInstance.SaveCharToDB(PlayerInstance.java:1531) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.Player.PlayerInstance.SaveAll(PlayerInstance.java:1191) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.MituyaProject.SavePlayerInstance(MituyaProject.java:629) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.MituyaProject.SaveAll(MituyaProject.java:619) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.Tool.Timer.AutoSave.run(AutoSave.java:48) [MituyaProject-5.6.jar:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
##     at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

[13:11:03] [Server thread/ERROR]: CreateDefaultCharToDB
java.sql.SQLException: Field 'uuid' doesn't have a default value
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at com.chantake.MituyaProject.Player.PlayerInstance.CreateCharTableToDB(PlayerInstance.java:1405) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.Player.PlayerInstance.LoadCharFromDB(PlayerInstance.java:1269) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.Player.PlayerInstance.Login(PlayerInstance.java:1121) [MituyaProject-5.6.jar:?]
    at com.chantake.MituyaProject.Bukkit.Listener.MituyaProjectPlayerListener.onPlayerJoin(MituyaProjectPlayerListener.java:301) [MituyaProject-5.6.jar:?]
    at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:263) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:148) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

**Comment by fumitti** [comment]
default value == Empty String
